# Generated by Django 3.1.2 on 2020-11-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='patients',
            field=models.ManyToManyField(null=True, to='app.Patient', verbose_name='Пациенты'),
        ),
        migrations.AddField(
            model_name='account',
            name='positions_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.positions', verbose_name='Должность'),
        ),
    ]
