# Generated by Django 3.1.2 on 2020-11-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201120_1259'),
        ('account', '0002_auto_20201116_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='patients',
            field=models.ManyToManyField(blank='True', to='app.Patient', verbose_name='Пациенты'),
        ),
    ]
