# Generated by Django 3.1.2 on 2020-11-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201126_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='doctor_admin',
            field=models.BooleanField(default=False, verbose_name='Доктор-администратор'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
