# Generated by Django 3.1.2 on 2020-11-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201128_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='doctor_admin',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Доктор-администратор'),
        ),
    ]
