# Generated by Django 3.1.2 on 2020-11-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201120_1349'),
        ('account', '0003_auto_20201120_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='disease',
            field=models.ManyToManyField(blank='True', to='app.Disease', verbose_name='Заболевания'),
        ),
    ]
