# Generated by Django 3.1.2 on 2020-11-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_disease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='disease',
            new_name='diseases',
        ),
    ]
