# Generated by Django 3.1.2 on 2020-11-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201125_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='doctor_admin',
            field=models.BooleanField(default=False, verbose_name='Доктор-администратор'),
        ),
    ]
