# Generated by Django 3.1.2 on 2020-11-26 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_disease', models.CharField(max_length=50, verbose_name='Наименование заболевания')),
                ('description_disease', models.TextField(verbose_name='Описание заболевания')),
                ('number_of_patients', models.IntegerField(default=0, null=True, verbose_name='Количество заболевших')),
                ('status_genetic_predisposition', models.BooleanField(default=False, verbose_name='Наличие генетических предрасположенностей')),
                ('description_genetic_predisposition', models.TextField(blank=True, default='-', null=True, verbose_name='Описание генетической предрасположенности')),
            ],
            options={
                'verbose_name': 'Заболевание',
                'verbose_name_plural': 'Заболевания',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_symptom', models.CharField(max_length=50, verbose_name='Наименование симптома')),
                ('description_symptom', models.CharField(max_length=200, verbose_name='Описание симптома')),
            ],
            options={
                'verbose_name': 'Симптом',
                'verbose_name_plural': 'Симптомы',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_patient', models.CharField(max_length=50, verbose_name='Фамилия пациента')),
                ('name_patient', models.CharField(max_length=50, verbose_name='Имя пациента')),
                ('middlename_patient', models.CharField(max_length=50, verbose_name='Отчество пациента')),
                ('birthday_patient', models.DateField(max_length=50, verbose_name='День рождение пациента')),
                ('gender_patient', models.CharField(max_length=50, verbose_name='Пол пациента')),
                ('enlightenment_patient', models.CharField(max_length=50, verbose_name='Санитарное просвящение пациента')),
                ('number_of_medical_card', models.CharField(max_length=50, verbose_name='Номер медицинской карты')),
                ('chronic_disease', models.CharField(max_length=250, null=True, verbose_name='Хронические заболевания')),
                ('description_recommendation', models.CharField(default='-', max_length=200, verbose_name='Описание рекомендации')),
                ('date_recommendation', models.DateField(blank=True, max_length=50, null=True, verbose_name='Дата выдачи рекомендации')),
                ('period_recommendation', models.DateField(blank=True, null=True, verbose_name='Период времени')),
                ('childhood_diseases', models.ManyToManyField(blank=True, related_name='childhood_diseases', to='app.Disease', verbose_name='Болезни детства')),
                ('fk_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('relatives_diseases', models.ManyToManyField(blank=True, related_name='relatives_diseases', to='app.Disease', verbose_name='Болезни у родственников')),
                ('symptoms_patient', models.ManyToManyField(blank=True, related_name='symptoms_patient', to='app.Symptom', verbose_name='Симптомы')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseases', models.ManyToManyField(related_name='MedicalRecords', to='app.Disease', verbose_name='Заболевание')),
                ('fk_patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Медицинская карта',
                'verbose_name_plural': 'Медицинские карты',
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(related_name='diseases', to='app.Symptom', verbose_name='Симптом'),
        ),
    ]
