# Generated by Django 3.1.2 on 2020-11-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='number_of_medical_card',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер медицинской карты'),
        ),
    ]
