# Generated by Django 3.1.2 on 2020-11-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201126_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='description_recommendation',
            field=models.CharField(blank=True, default='-', max_length=200, null=True, verbose_name='Описание рекомендации'),
        ),
    ]
