# Generated by Django 3.1.2 on 2020-11-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201116_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='number_of_medical_card',
            field=models.CharField(max_length=50, verbose_name='Номер медицинской карты'),
        ),
    ]
