# Generated by Django 3.1.2 on 2020-11-20 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20201117_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='childhood_diseases',
            field=models.ManyToManyField(blank=True, related_name='childhood_diseases', to='app.Disease', verbose_name='Болезни детства'),
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_disease',
            field=models.CharField(max_length=250, null=True, verbose_name='Хронические заболевания'),
        ),
        migrations.AddField(
            model_name='patient',
            name='relatives_diseases',
            field=models.ManyToManyField(blank=True, related_name='relatives_diseases', to='app.Disease', verbose_name='Болезни у родственников'),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='symptoms', to='app.Symptom', verbose_name='Симптом'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='number_of_patients',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество заболевших'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='fk_distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
        ),
    ]
