# Generated by Django 3.1.2 on 2020-11-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201126_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='qwerty@gmail.com', max_length=254, verbose_name='Почта'),
        ),
    ]
