# Generated by Django 3.1.2 on 2020-11-26 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='Тема сообщения')),
                ('problem_description', models.TextField(max_length=5000, verbose_name='Описание проблемы')),
                ('file_inform', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('email_addres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient', verbose_name='Eamil пациента')),
            ],
            options={
                'verbose_name': 'Оповещение пациента',
                'verbose_name_plural': 'Оповещения пациентов',
            },
        ),
    ]
