# Generated by Django 3.1.2 on 2020-11-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201127_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inform',
            name='file_inform',
        ),
    ]
