# Generated by Django 3.1.2 on 2020-11-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_inform_file_inform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday_patient',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='День рождение пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='enlightenment_patient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Санитарное просвящение пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender_patient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Пол пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middlename_patient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name_patient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number_of_medical_card',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер медицинской карты'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname_patient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия пациента'),
        ),
    ]
