# Generated by Django 3.1.2 on 2020-11-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201127_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='email_addres',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='Email пользователя'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='problem_description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тема сообщения'),
        ),
    ]
