# Generated by Django 3.1.2 on 2020-11-28 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20201127_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday_patient',
            field=models.DateField(max_length=50, null=True, verbose_name='День рождение пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_recommendation',
            field=models.DateField(max_length=50, null=True, verbose_name='Дата выдачи рекомендации'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description_recommendation',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='Описание рекомендации'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='enlightenment_patient',
            field=models.CharField(max_length=50, null=True, verbose_name='Санитарное просвящение пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fk_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.account', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middlename_patient',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name_patient',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='period_recommendation',
            field=models.DateField(null=True, verbose_name='Период времени'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname_patient',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия пациента'),
        ),
    ]
