# Generated by Django 3.1.2 on 2020-11-28 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_auto_20201128_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fk_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
        ),
    ]
