# Generated by Django 3.1.2 on 2020-11-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201128_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='number_of_medical_card',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер медицинской карты'),
        ),
    ]
