# Generated by Django 3.1.2 on 2020-11-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201128_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='period_recommendation',
            field=models.DateField(max_length=50, null=True, verbose_name='Период времени'),
        ),
    ]
