# Generated by Django 3.1.2 on 2020-11-28 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_auto_20201128_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday_patient',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='День рождение пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chronic_disease',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Хронические заболевания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_recommendation',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='Дата выдачи рекомендации'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description_recommendation',
            field=models.CharField(blank=True, default='-', max_length=200, null=True, verbose_name='Описание рекомендации'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fk_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middlename_patient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name_patient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='period_recommendation',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='Период времени'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname_patient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия пациента'),
        ),
    ]
