# Generated by Django 3.1.2 on 2020-11-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201128_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='email_addres',
            field=models.EmailField(max_length=250, verbose_name='Email пользователя'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='problem_description',
            field=models.TextField(max_length=5000, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='topic',
            field=models.CharField(max_length=50, verbose_name='Тема сообщения'),
        ),
    ]
