# Generated by Django 3.1.2 on 2020-11-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201128_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='description_recommendation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание рекомендации'),
        ),
    ]
