# Generated by Django 3.1.2 on 2020-11-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_error', models.CharField(max_length=50, verbose_name='Тип ошибки')),
                ('description_type', models.TextField(max_length=250, verbose_name='Описание типа ошибки')),
            ],
            options={
                'verbose_name': 'Тип ошибоки',
                'verbose_name_plural': 'Типы ошибок',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='Тема сообщения')),
                ('problem_description', models.TextField(max_length=5000, verbose_name='Описание проблемы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('type_errors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='report.typeerrors', verbose_name='Типы ошибок')),
            ],
            options={
                'verbose_name': 'Сообщение об ошибке',
                'verbose_name_plural': 'Сообщения об ошибках',
            },
        ),
    ]
