# Generated by Django 3.1.2 on 2020-11-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20201122_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='report',
            name='problem_description',
            field=models.TextField(max_length=5000, verbose_name='Описание проблемы'),
        ),
    ]
